### ISSUE TITLE
Colors are wrong.

### ISSUE THREAD

**Issue by xonecas** [jscappini/material.vim#1]
Maybe this theme depends on a specific terminal theme?

<img width="1276" alt="screen shot 2015-10-06 at 16 23 28" src="https://cloud.githubusercontent.com/assets/444680/10325491/a3ade11a-6c46-11e5-9088-b3041155b95e.png">

**Comment by jacobhenke** [comment]
+1

**Comment by jscappini** [comment]
Erm, maybe colors are not that right at all but your issue isn't that. Please take a look at this vi.stackexchange thread:

http://vi.stackexchange.com/questions/2436/why-does-the-same-color-scheme-look-better-in-gvim-than-cygwin/2451#2451

And as I said on this repo description, it works only on GVim (and maybe on MacVim), and you shouldn't expect it to work on terminal Vim. But hey, PR are welcome if you want to make it works! :smiley:
